name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run every Monday at 08:00
  schedule:
    - cron: "0 8 * * 1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ pharo9, pharo10, pharo11, pharo12 ]
        group: [ Full ]
        tests: [ Roassal ]
        os: [ ubuntu-latest ]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # depth 0 will download all the repository history
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # This will delete roassal and numeric scales and it executes the tests again
      - name: Run pharo Tests
        id: tests
        uses: akevalion/PharoTestsAction@v1
        with:
          removes-repo: 'Roassal, Numeric'
          baseline: 'Roassal'
          group: ${{matrix.group}}
          tests: ${{matrix.tests}}
          pharo: ${{matrix.smalltalk}}
